# Generated by Django 5.2.16 on 2026-08-23 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', help_text='Short candidate introduction or learning target.', max_length=500)),
                ('target_exam', models.CharField(blank=True, choices=[('jft_basic', 'JFT-Basic (A2 Standard)'), ('ssw_nursing', 'SSW: Nursing Care (介護)'), ('ssw_food', 'SSW: Food Service (外食業)'), ('ssw_agriculture', 'SSW: Agriculture (農業)'), ('ssw_construction', 'SSW: Construction (建設業)'), ('ssw_manufacturing', 'SSW: Manufacturing (製造業)'), ('ssw_accommodation', 'SSW: Accommodation (宿泊業)'), ('jlpt_n4', 'JLPT N4'), ('jlpt_n3', 'JLPT N3'), ('other', 'Other Examination')], default='jft_basic', max_length=40)),
                ('japanese_level', models.CharField(blank=True, choices=[('n5', 'Beginner (N5 / A1)'), ('n4', 'Elementary (N4 / A2)'), ('n3', 'Intermediate (N3 / B1)'), ('n2', 'Upper Intermediate (N2 / B2)'), ('n1', 'Advanced (N1 / C1)')], default='n4', max_length=20)),
                ('location', models.CharField(blank=True, default='', help_text='Country or City (e.g. Dhaka, Yangon, Jakarta)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
