# Generated by Django 5.2.17 on 2026-09-05 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text="Candidate's country of residence or nationality", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_source',
            field=models.CharField(choices=[('user', 'User Selected'), ('ip', 'IP Estimated'), ('unknown', 'Unknown')], default='unknown', help_text='Source of the country information: user (explicit), ip (estimated), unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_known_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Last recorded client IP address for security audit & geolocation', null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw token', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where reset was requested', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash', 'is_used'], name='accounts_pa_token_h_dab8fb_idx')],
            },
        ),
    ]
