# Generated by Django 5.2.16 on 2026-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_actual_exam_demo',
            field=models.BooleanField(default=False, help_text='If checked, candidates must complete the official Introduction part before starting Section 1. Otherwise starts directly on Question 1.', verbose_name='Actual Exam Demo'),
        ),
    ]
