# Generated by Django 5.2.16 on 2026-07-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_is_actual_exam_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, help_text='e.g. How do you write the underlined kanji word in hiragana? Choose the correct one.', verbose_name='Instruction / Pre-prompt'),
        ),
        migrations.AddField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Custom JSON mapping for 9 languages e.g. {'English': '...', 'Chinese': '...', 'Indonesian': '...'}"),
        ),
    ]
