# Generated by Django 5.2.16 on 2026-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_question_instruction_question_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1, help_text='Points awarded for getting this question correct (e.g. 1 mark for simple vocabulary, 2-5 marks for hard listening/reading questions).', verbose_name='Question Marks / Weight'),
        ),
    ]
