# Generated by Django 5.2.16 on 2026-08-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('image_audio', 'Image + Audio')], max_length=16),
        ),
    ]
