# Generated by Django 5.2.16 on 2026-08-02 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_add_image_audio_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Admin label, e.g. 'Reading Passage 1' or 'Listening Conversation 3'", max_length=255)),
                ('instruction', models.TextField(blank=True, help_text="Shared instruction for all questions in this group, e.g. 'You are reading a town magazine. Answer questions (1) and (2).'")),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='groups/audio/')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='tests.test')),
            ],
            options={
                'verbose_name': 'Question Group',
                'verbose_name_plural': 'Question Groups',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional. Link to a shared image/audio passage. Leave blank for standalone questions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tests.questiongroup'),
        ),
    ]
