# Generated by Django 5.2.16 on 2026-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_add_question_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='groups/images/'),
        ),
    ]
