# Generated by Django 5.2.16 on 2026-08-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_allow_filefield_for_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='options/images/'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
