# Generated by Django 5.2.16 on 2026-08-11 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_answeroption_image_alter_answeroption_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, help_text='To show multiple prompts/questions under one shared image/passage, select or create (+) a Question Group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tests.questiongroup'),
        ),
        migrations.AlterField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, help_text='e.g. How do you write the __underlined__ kanji word in hiragana? Use __word__ to underline specific words.', verbose_name='Instruction / Pre-prompt'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.TextField(blank=True, help_text='The question text. Use __word__ to underline specific words (e.g. 水道が __こわれた__ ときは).'),
        ),
    ]
