# Generated by Django 5.2.16 on 2026-08-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_underline_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Custom JSON mapping for 10 languages e.g. {'Bengali': '...', 'English': '...', 'Chinese': '...', 'Indonesian': '...'}"),
        ),
    ]
