# Generated by Django 5.2.16 on 2026-08-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_question_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_script',
            field=models.TextField(blank=True, help_text='Dialogue script for auto-generating audio (e.g. [Nanami], [こんにちは], [Keita], [こんにちは]).', verbose_name='Audio Script / Dialogue'),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='audio_script',
            field=models.TextField(blank=True, help_text='Shared dialogue script for auto-generating group audio (e.g. [Nanami], [こんにちは], [Keita], [こんにちは]).', verbose_name='Audio Script / Dialogue'),
        ),
        migrations.AlterField(
            model_name='question',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text="Custom JSON mapping for 10 languages e.g. {'Bengali': '...', 'English': '...', 'Chinese': '...', 'Indonesian': '...'}"),
        ),
    ]
