# Generated by Django 5.2.16 on 2026-08-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_question_audio_script_questiongroup_audio_script_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline for the notice or announcement.', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Short summary preview for notification cards.')),
                ('content', models.TextField(blank=True, help_text='Detailed announcement body (supports markdown and paragraphs).')),
                ('notice_type', models.CharField(choices=[('general', 'General Notice'), ('exam_alert', 'Exam Alert'), ('material', 'PDF Study Material'), ('update', 'System Update'), ('event', 'Event / Workshop')], default='general', help_text='Category of this notice.', max_length=32)),
                ('target_audience', models.CharField(choices=[('all', 'All Visitors & Candidates'), ('registered', 'Registered Students Only'), ('jft', 'JFT-Basic Students'), ('ssw', 'SSW Skill Test Students')], default='all', help_text='Target audience filter.', max_length=32)),
                ('image', models.FileField(blank=True, help_text='Banner/Flyer image for the notice or card header.', null=True, upload_to='notices/images/')),
                ('pdf_file', models.FileField(blank=True, help_text='Downloadable PDF study guide, past questions, or vocabulary sheet.', null=True, upload_to='notices/pdfs/')),
                ('file_size_text', models.CharField(blank=True, help_text="Human-readable file size (e.g. '2.4 MB PDF'). Auto-calculated if blank.", max_length=64)),
                ('action_url', models.CharField(blank=True, help_text="Custom link URL (e.g. '/test/8' or external registration portal).", max_length=500)),
                ('action_button_text', models.CharField(blank=True, default='View Details', help_text="Action button label (e.g. 'Download PDF Guide', 'Take Mock Test', 'Read Notice').", max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Visible to candidates on public API.')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin to the top of notice board and show in hero alert banner.')),
                ('show_as_popup', models.BooleanField(default=False, help_text='Show as high-priority popup alert modal when candidates enter site.')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first).')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date after which the notice automatically hides.', null=True)),
                ('related_test', models.ForeignKey(blank=True, help_text='Link directly to a specific mock test.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='tests.test')),
            ],
            options={
                'verbose_name': 'Notice & Study Material',
                'verbose_name_plural': 'Notices & Study Materials',
                'ordering': ['-is_pinned', 'order_index', '-created_at'],
            },
        ),
    ]
