# Generated by Django 5.2.16 on 2026-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='scheduled_release_at',
            field=models.DateTimeField(blank=True, help_text='Optional future date and time when this test will be unlocked for candidates. If set in the future, the test card displays a live countdown timer and a blurred lock preview.', null=True, verbose_name='Scheduled Release Date & Time'),
        ),
    ]
