# Generated by Django 5.2.17 on 2026-09-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_test_scheduled_release_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('script_vocab', 'Script and Vocabulary'), ('conversation', 'Conversation and Expression'), ('listening', 'Listening Comprehension'), ('reading', 'Reading Comprehension'), ('audio', 'Audio Comprehension & Typing (Phase 1)'), ('occupational', 'Occupational / Practical Skills (Phase 2)')], default='script_vocab', max_length=32),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('image_audio', 'Image + Audio'), ('typing', 'Typing (Text Input)'), ('audio_typing', 'Audio + Typing')], max_length=16),
        ),
    ]
