'use client';

import React from 'react';
import Link from 'next/link';
import {
  ShieldAlert,
  ShieldCheck,
  Scale,
  AlertTriangle,
  Building2,
  FileCheck2,
  ExternalLink,
  Info,
} from 'lucide-react';

const DISCLAIMER_SECTIONS = [
  {
    title: '1. Independent Educational Preparatory Platform',
    content: `Gakkou No Shiken (学校の試験 - www.gakkounoshiken.site) is an independent private educational and diagnostic preparation platform developed for students and professionals preparing for Japanese language and technical exams. We are not owned, operated, funded, or administratively affiliated with any government entity, testing agency, or official certification board in Japan or overseas.`,
  },
  {
    title: '2. Non-Affiliation with The Japan Foundation & JEES',
    content: `The "Japan Foundation Test for Basic Japanese" (JFT-Basic) is organized and administered globally by The Japan Foundation (独立行政法人国際交流基金) and Japan Educational Exchanges and Services (JEES).
• Gakkou No Shiken is an independent educational training service and is NOT affiliated with, sponsored by, or endorsed by The Japan Foundation or JEES.
• The terms "JFT-Basic", "JF Standard for Japanese-Language Education", and associated descriptors are referenced strictly under fair-use nominative principles for academic study and exam preparation purposes.`,
  },
  {
    title: '3. Non-Affiliation with Prometric Inc.',
    content: `Prometric Inc. and Prometric Japan Co., Ltd. are third-party test delivery vendors contracted to administer computer-based tests for JFT-Basic and Specified Skilled Worker (SSW) exams worldwide.
• Gakkou No Shiken is NOT an official Prometric testing center and is NOT affiliated with Prometric Inc.
• Our CBT mock interface is an independently developed simulation engine engineered to familiarize students with computer-based test layouts, timers, and navigation rules.
• Candidates must register for their actual examination directly through the official Prometric website (www.prometric-jp.com) and purchase official test vouchers through designated local channels.`,
  },
  {
    title: '4. Non-Affiliation with Japanese Government Ministries',
    content: `Specified Skilled Worker (SSW - 特定技能) examinations are defined under statutory frameworks established by Japanese government bodies, including the Ministry of Foreign Affairs (MOFA), the Ministry of Health, Labour and Welfare (MHLW), the Ministry of Agriculture, Forestry and Fisheries (MAFF), and the Immigration Services Agency of Japan (ISA).
• Gakkou No Shiken is not affiliated with, accredited by, or authorized by any Japanese ministry or embassy.
• Practice questions, sector guides, and occupational mock tests are developed independently by our curriculum team using public syllabus standards.`,
  },
  {
    title: '5. Simulated Scores & CEFR Diagnostics Nature',
    content: `The scaled scores (10–250 points) and pass/fail indicators generated on Gakkou No Shiken are mathematical simulations modeled after public Item Response Theory (IRT) benchmarks.
• Diagnostic Practice Only: Mock test score certificates generated on this website are for candidate self-evaluation, diagnostic practice, and classroom progress tracking only.
• Not an Official Credential: Score reports generated by Gakkou No Shiken cannot be submitted to the Immigration Services Agency of Japan, visa processing centers, or prospective employers as official proof of language proficiency.
• No Score Guarantee: Achieving a passing score (e.g. 200+ points) on our mock exams does not guarantee that a candidate will achieve a passing mark on their official examination day.`,
  },
  {
    title: '6. No Visa, Employment, or Certificate of Eligibility (COE) Guarantee',
    content: `Gakkou No Shiken is an educational learning technology platform. We do not provide immigration legal counseling, work visa sponsorship, recruiting agency services, or guarantees of overseas employment. Passing a mock test on our website does not grant or guarantee a Japanese Specified Skilled Worker (SSW) or Technical Intern visa.`,
  },
  {
    title: '7. Accuracy of Test Center & Voucher Information',
    content: `We provide informational guides on test center locations (e.g., UTC Dhaka, Chittagong, Tokyo), booking procedures, and voucher purchase guidelines in local currencies (BDT) as a public service for candidates.
• While we make every reasonable effort to keep venue addresses, fee schedules, and registration timelines current, official test dates and policies may change without notice.
• Candidates are strongly advised to verify final test dates, venue addresses, and ID requirements on the official Prometric candidate portal.`,
  },
];

export default function DisclaimerPage() {
  return (
    <div className="space-y-12 sm:space-y-16 animate-fade-in pb-16 font-sans">
      {/* Hero Header */}
      <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-[#0c1222] border border-slate-800/80 p-6 sm:p-12 lg:p-14 shadow-2xl text-white">
        <div className="pointer-events-none absolute -top-24 -right-24 w-96 h-96 rounded-full bg-amber-500/15 blur-3xl" />
        <div className="pointer-events-none absolute -bottom-24 -left-24 w-96 h-96 rounded-full bg-slate-700/20 blur-3xl" />

        <div className="relative z-10 max-w-3xl space-y-4">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-amber-500/15 text-amber-300 border border-amber-500/30 text-xs font-black uppercase tracking-wider">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
            <span>Academic Fair Use &amp; Regulatory Transparency</span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-black tracking-tight leading-tight">
            Educational Disclaimer
          </h1>

          <p className="text-xs sm:text-sm text-slate-400 font-medium leading-relaxed max-w-2xl">
            Last Updated: September 2026 • Please review this notice detailing our independent preparatory status, non-affiliation with testing organizations, and the diagnostic nature of our mock scores.
          </p>
        </div>
      </section>

      {/* Main Content Layout */}
      <div className="max-w-4xl mx-auto bg-white dark:bg-slate-900/90 rounded-3xl border border-slate-200/90 dark:border-slate-800 p-6 sm:p-10 lg:p-12 shadow-xl space-y-8">
        {/* Important Warning Banner */}
        <div className="p-5 sm:p-6 rounded-2xl bg-amber-50/80 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800/80 text-amber-900 dark:text-amber-200 space-y-2">
          <div className="flex items-center gap-2.5 font-black text-sm">
            <ShieldAlert className="w-5 h-5 text-amber-600 dark:text-amber-400 shrink-0" />
            <span>Notice of Independent Operation</span>
          </div>
          <p className="text-xs sm:text-sm text-amber-800 dark:text-amber-300 leading-relaxed">
            Gakkou No Shiken is an independent educational training platform. We are <strong>NOT affiliated with, authorized by, endorsed by, or in any way officially connected</strong> with The Japan Foundation (国際交流基金), Prometric Inc., or the Japanese Government.
          </p>
        </div>

        {/* Disclaimer Sections */}
        <div className="space-y-8 divide-y divide-slate-100 dark:divide-slate-800">
          {DISCLAIMER_SECTIONS.map((sec, idx) => (
            <section key={idx} className="pt-8 first:pt-0 space-y-2.5">
              <h3 className="text-base sm:text-lg font-black text-slate-900 dark:text-white tracking-tight">
                {sec.title}
              </h3>
              <div className="text-xs sm:text-sm text-slate-600 dark:text-slate-400 leading-relaxed whitespace-pre-line space-y-2">
                {sec.content}
              </div>
            </section>
          ))}
        </div>

        {/* Bottom Contact Guidance */}
        <div className="p-6 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/80 flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="space-y-1 text-center sm:text-left">
            <h4 className="text-sm font-bold text-slate-900 dark:text-white">
              Questions Regarding This Disclaimer?
            </h4>
            <p className="text-xs text-slate-500 dark:text-slate-400">
              Our administrative and compliance desk is available to assist you.
            </p>
          </div>
          <Link
            href="/contact"
            className="inline-flex items-center gap-2 px-4 py-2.5 bg-slate-900 dark:bg-slate-800 hover:bg-slate-800 dark:hover:bg-slate-700 text-white text-xs font-bold rounded-xl shadow-xs transition-colors shrink-0"
          >
            <span>Contact Support Desk</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </Link>
        </div>
      </div>
    </div>
  );
}
