# Generated by Django 5.2.16 on 2026-07-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic'), ('skill', 'Skill')], default='basic', max_length=16),
        ),
    ]
