# Generated by Django 5.2.16 on 2026-07-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('script_vocab', 'Script and Vocabulary'), ('conversation', 'Conversation and Expression'), ('listening', 'Listening Comprehension'), ('reading', 'Reading Comprehension')], default='script_vocab', max_length=32),
        ),
    ]
