# Generated by Django 5.2.16 on 2026-07-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_question_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
